### ISSUE TITLE
On Windows, ksguid string replacement causes a crash now

### ISSUE THREAD

**Issue by ghost** [jgsogo/conan-portaudio#10]
Hi Javier,

I don't know if there's something different in the portaudio source now but I suddenly got a crash when building the master branch, as well as the v190600.20161030 branch:

```
ERROR: portaudio/master@jgsogo/stable: Error in build() method, line 64
        replace_in_file(os.path.join(self.FOLDER_NAME, "CMakeLists.txt"), "ADD_DEFINITIONS(-D_CRT_SECURE_NO_WARNINGS)", "ADD_DEFINITIONS(-D_CRT_SECURE_NO_WARNINGS -DPAWIN_WDMKS_NO_KSGUID_LIB)")
        ConanException: replace_in_file didn't find pattern 'ADD_DEFINITIONS(-D_CRT_SECURE_NO_WARNINGS)' in 'portaudio\CMakeLists.txt' file.
```
By commenting out line 64 of conanfile.py the package gets built successfully and it seems to work, despite missing the ksguid-disabling code. I have just figured this out on the fly, so I don't know what implications the fix I've done on my side may have (which is why I have not introduced a pull request), but I thought to let you know.

**Comment by jgsogo** [comment]
It is working again (fixed as you suggested). I have also updated Conan related files to match the layout I'm using for other packages and the README file to show a build status matrix (right now there is only one red in MacOS I'll try to address soon).

Also I've scheduled Travis to run once a month for all branches to get notified if something goes wrong.

Thanks!

**Comment by ghost** [comment]
Great!

Thank you too!
