### ISSUE TITLE
New portaudio version

### ISSUE THREAD

**Issue by ghost** [jgsogo/conan-portaudio#4]
There's a new portaudio release candidate version (v190600_20161001):

http://www.portaudio.com/download.html

I'm just saying... :grin:

**Comment by jgsogo** [comment]
An easy commit, but too many changes just to set a new version.... 

Someone should consider building an script: it should take a template and a config file from master branch and generate branches for each version using the template and substituting values here and there. It should be easy enough.

**Comment by ghost** [comment]
Yeah, it's true that there's a bit of repetition. That sounds like a pretty good idea.

Other than that, I see you're building right now! 😃

**Comment by ghost** [comment]
I'm wondering if this new version stops using some deprecated OSX libraries. And if it stops having the weird behaviour or Debian with PulseAudio.

**Comment by ghost** [comment]
Thanks for the new version! I've linked to it and all my builds are working. I am using it on the develop branch of small3d for now (/testing package) and will officially be using it also, in the next release. 👍
