### ISSUE TITLE
FindPortaudio.cmake to FindPORTAUDIO.cmake for Debian

### ISSUE THREAD

**Issue by ghost** [jgsogo/conan-portaudio#5]
Hi Javier,

Could you by any chance change the name of FindPortaudio.cmake to FindPORTAUDIO.cmake in your package on conan.io? Debian is having some trouble with cmake modules that don't have the library part in all capitals.

Thanks,

Dimitri

**Comment by jgsogo** [comment]
I don't think caps should be a problem. There are a lot of modules with not all capital letters: https://cmake.org/cmake/help/latest/manual/cmake-modules.7.html

What's the issue your are facing?

**Comment by ghost** [comment]
My mistake! I wasn't aware of this. I thought all capitals was standard and I was using them everywhere. I'll close this request now, and shut my mouth 😸
